[package]
name = "tooling"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10.8"
clap = { version = "4.5.34", features = ["derive"] }
reqwest = {version = "0.12.15", features = ["blocking"]}
